//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace quickDBExplorer {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class textHistory : DataSet {
        
        private textHistoryDataDataTable tabletextHistoryData;
        
        public textHistory() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected textHistory(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["textHistoryData"] != null)) {
                    this.Tables.Add(new textHistoryDataDataTable(ds.Tables["textHistoryData"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public textHistoryDataDataTable textHistoryData {
            get {
                return this.tabletextHistoryData;
            }
        }
        
        public override DataSet Clone() {
            textHistory cln = ((textHistory)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["textHistoryData"] != null)) {
                this.Tables.Add(new textHistoryDataDataTable(ds.Tables["textHistoryData"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tabletextHistoryData = ((textHistoryDataDataTable)(this.Tables["textHistoryData"]));
            if ((this.tabletextHistoryData != null)) {
                this.tabletextHistoryData.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "textHistory";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/textHistory.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tabletextHistoryData = new textHistoryDataDataTable();
            this.Tables.Add(this.tabletextHistoryData);
        }
        
        private bool ShouldSerializetextHistoryData() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void textHistoryDataRowChangeEventHandler(object sender, textHistoryDataRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class textHistoryDataDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnKeyNo;
            
            private DataColumn columnKeyValue;
            
            private DataColumn columnDataValue;
            
            internal textHistoryDataDataTable() : 
                    base("textHistoryData") {
                this.InitClass();
            }
            
            internal textHistoryDataDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn KeyNoColumn {
                get {
                    return this.columnKeyNo;
                }
            }
            
            internal DataColumn KeyValueColumn {
                get {
                    return this.columnKeyValue;
                }
            }
            
            internal DataColumn DataValueColumn {
                get {
                    return this.columnDataValue;
                }
            }
            
            public textHistoryDataRow this[int index] {
                get {
                    return ((textHistoryDataRow)(this.Rows[index]));
                }
            }
            
            public event textHistoryDataRowChangeEventHandler textHistoryDataRowChanged;
            
            public event textHistoryDataRowChangeEventHandler textHistoryDataRowChanging;
            
            public event textHistoryDataRowChangeEventHandler textHistoryDataRowDeleted;
            
            public event textHistoryDataRowChangeEventHandler textHistoryDataRowDeleting;
            
            public void AddtextHistoryDataRow(textHistoryDataRow row) {
                this.Rows.Add(row);
            }
            
            public textHistoryDataRow AddtextHistoryDataRow(string KeyValue, string DataValue) {
                textHistoryDataRow rowtextHistoryDataRow = ((textHistoryDataRow)(this.NewRow()));
                rowtextHistoryDataRow.ItemArray = new object[] {
                        null,
                        KeyValue,
                        DataValue};
                this.Rows.Add(rowtextHistoryDataRow);
                return rowtextHistoryDataRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                textHistoryDataDataTable cln = ((textHistoryDataDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new textHistoryDataDataTable();
            }
            
            internal void InitVars() {
                this.columnKeyNo = this.Columns["KeyNo"];
                this.columnKeyValue = this.Columns["KeyValue"];
                this.columnDataValue = this.Columns["DataValue"];
            }
            
            private void InitClass() {
                this.columnKeyNo = new DataColumn("KeyNo", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnKeyNo);
                this.columnKeyValue = new DataColumn("KeyValue", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnKeyValue);
                this.columnDataValue = new DataColumn("DataValue", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDataValue);
                this.columnKeyNo.AutoIncrement = true;
                this.columnKeyNo.AutoIncrementSeed = 1;
                this.CaseSensitive = true;
            }
            
            public textHistoryDataRow NewtextHistoryDataRow() {
                return ((textHistoryDataRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new textHistoryDataRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(textHistoryDataRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.textHistoryDataRowChanged != null)) {
                    this.textHistoryDataRowChanged(this, new textHistoryDataRowChangeEvent(((textHistoryDataRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.textHistoryDataRowChanging != null)) {
                    this.textHistoryDataRowChanging(this, new textHistoryDataRowChangeEvent(((textHistoryDataRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.textHistoryDataRowDeleted != null)) {
                    this.textHistoryDataRowDeleted(this, new textHistoryDataRowChangeEvent(((textHistoryDataRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.textHistoryDataRowDeleting != null)) {
                    this.textHistoryDataRowDeleting(this, new textHistoryDataRowChangeEvent(((textHistoryDataRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovetextHistoryDataRow(textHistoryDataRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class textHistoryDataRow : DataRow {
            
            private textHistoryDataDataTable tabletextHistoryData;
            
            internal textHistoryDataRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletextHistoryData = ((textHistoryDataDataTable)(this.Table));
            }
            
            public int KeyNo {
                get {
                    try {
                        return ((int)(this[this.tabletextHistoryData.KeyNoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletextHistoryData.KeyNoColumn] = value;
                }
            }
            
            public string KeyValue {
                get {
                    try {
                        return ((string)(this[this.tabletextHistoryData.KeyValueColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletextHistoryData.KeyValueColumn] = value;
                }
            }
            
            public string DataValue {
                get {
                    try {
                        return ((string)(this[this.tabletextHistoryData.DataValueColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("値は DBNull であるため、取得できません。", e);
                    }
                }
                set {
                    this[this.tabletextHistoryData.DataValueColumn] = value;
                }
            }
            
            public bool IsKeyNoNull() {
                return this.IsNull(this.tabletextHistoryData.KeyNoColumn);
            }
            
            public void SetKeyNoNull() {
                this[this.tabletextHistoryData.KeyNoColumn] = System.Convert.DBNull;
            }
            
            public bool IsKeyValueNull() {
                return this.IsNull(this.tabletextHistoryData.KeyValueColumn);
            }
            
            public void SetKeyValueNull() {
                this[this.tabletextHistoryData.KeyValueColumn] = System.Convert.DBNull;
            }
            
            public bool IsDataValueNull() {
                return this.IsNull(this.tabletextHistoryData.DataValueColumn);
            }
            
            public void SetDataValueNull() {
                this[this.tabletextHistoryData.DataValueColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class textHistoryDataRowChangeEvent : EventArgs {
            
            private textHistoryDataRow eventRow;
            
            private DataRowAction eventAction;
            
            public textHistoryDataRowChangeEvent(textHistoryDataRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public textHistoryDataRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
